#!/usr/bin/env python3
"""Generate skills/lambda-schema/references/schema-reference.md from the LinkML schema.

Run this whenever lambda-ber-schema changes so the skill's cheat sheet stays
true to the schema. It reads the YAML directly and needs only PyYAML.

    python scripts/gen_schema_reference.py [--schema-dir PATH] [--out PATH]

The schema dir defaults to $LAMBDA_SCHEMA_DIR, then ../lambda-ber-schema,
then ~/lambda-ber-schema.
"""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

import yaml

HERE = Path(__file__).resolve().parent
TOOLKIT = HERE.parent
DEFAULT_OUT = TOOLKIT / "skills" / "lambda-schema" / "references" / "schema-reference.md"


def find_schema_dir(explicit: str | None) -> Path:
    candidates = [explicit, os.environ.get("LAMBDA_SCHEMA_DIR"),
                  TOOLKIT.parent / "lambda-ber-schema", Path.home() / "lambda-ber-schema"]
    for c in candidates:
        if c and (Path(c) / "src/lambda_ber_schema/schema/lambda_ber_schema.yaml").exists():
            return Path(c)
    sys.exit("could not find a lambda-ber-schema checkout; pass --schema-dir")


def load_schemas(schema_dir: Path) -> dict:
    """Merge the main schema with its local imports into one dict of classes/enums."""
    base = schema_dir / "src/lambda_ber_schema/schema"
    main = yaml.safe_load((base / "lambda_ber_schema.yaml").read_text())
    classes = dict(main.get("classes") or {})
    enums = dict(main.get("enums") or {})
    slots = dict(main.get("slots") or {})
    for imp in main.get("imports") or []:
        if imp.startswith("linkml:"):
            continue
        p = base / f"{imp}.yaml"
        if not p.exists():
            continue
        sub = yaml.safe_load(p.read_text())
        for k in list((sub.get("classes") or {}).items()):
            classes.setdefault(k[0], k[1])
        for k in list((sub.get("enums") or {}).items()):
            enums.setdefault(k[0], k[1])
        for k in list((sub.get("slots") or {}).items()):
            slots.setdefault(k[0], k[1])
    return {"meta": main, "classes": classes, "enums": enums, "slots": slots}


def one_line(text: str | None, limit: int = 160) -> str:
    if not text:
        return ""
    t = " ".join(str(text).split())
    return t if len(t) <= limit else t[: limit - 1].rstrip() + "…"


def attrs_of(cls: dict, classes: dict, slots: dict) -> dict:
    """Own attributes plus inherited ones, child overriding parent."""
    out: dict = {}
    parent = cls.get("is_a")
    if parent and parent in classes:
        out.update(attrs_of(classes[parent], classes, slots))
    for s in cls.get("slots") or []:
        out[s] = dict(slots.get(s) or {})
    for name, spec in (cls.get("attributes") or {}).items():
        out[name] = dict(spec or {})
    for name, spec in (cls.get("slot_usage") or {}).items():
        out.setdefault(name, {}).update(spec or {})
    return out


def classify(classes: dict) -> dict[str, list[str]]:
    groups = {"Container": [], "Entity tables": [], "Association tables": [],
              "Instruments": [], "Supporting / value classes": [], "Other": []}
    for name, c in classes.items():
        parent = c.get("is_a") or ""
        if name == "Dataset":
            groups["Container"].append(name)
        elif name.endswith("Association"):
            groups["Association tables"].append(name)
        elif "Instrument" in name:
            groups["Instruments"].append(name)
        elif parent in ("NamedThing",) or name in ("NamedThing",):
            groups["Entity tables"].append(name)
        elif c.get("abstract") or c.get("mixin"):
            groups["Other"].append(name)
        else:
            groups["Supporting / value classes"].append(name)
    return {k: sorted(v) for k, v in groups.items() if v}


def render(schemas: dict, schema_dir: Path) -> str:
    meta, classes, enums, slots = (schemas[k] for k in ("meta", "classes", "enums", "slots"))
    version = meta.get("version", "unversioned")
    lines: list[str] = []
    w = lines.append
    w("# lambda-ber-schema reference")
    w("")
    w(f"Generated by `scripts/gen_schema_reference.py` from `{schema_dir.name}` "
      f"(schema version `{version}`). Do not edit by hand; regenerate.")
    w("")
    w("Contents: [Dataset slots](#dataset) · [Classes by group](#classes-by-group) · "
      "[Per-class detail](#per-class-detail) · [Enums](#enums)")
    w("")

    # Dataset
    ds = classes.get("Dataset")
    if ds:
        w("## Dataset")
        w("")
        w(one_line(ds.get("description"), 400))
        w("")
        w("| slot | range | multivalued | required |")
        w("|---|---|---|---|")
        for n, a in attrs_of(ds, classes, slots).items():
            w(f"| `{n}` | {a.get('range', '')} | {'yes' if a.get('multivalued') else ''} | "
              f"{'yes' if a.get('required') else ''} |")
        w("")

    # Groups
    groups = classify(classes)
    w("## Classes by group")
    w("")
    for g, names in groups.items():
        w(f"**{g}**: " + ", ".join(f"`{n}`" for n in names))
        w("")

    # Per class
    w("## Per-class detail")
    w("")
    w("Required slots are marked with `*`. Ranges that are enums link to the enum section.")
    w("")
    for name in sorted(classes):
        c = classes[name]
        a = attrs_of(c, classes, slots)
        req = [n for n, s in a.items() if s.get("required")]
        w(f"### {name}")
        parent = c.get("is_a")
        head = []
        if parent:
            head.append(f"is_a `{parent}`")
        if c.get("abstract"):
            head.append("abstract")
        if c.get("mixin"):
            head.append("mixin")
        if head:
            w("_" + ", ".join(head) + "_")
        w("")
        d = one_line(c.get("description"), 300)
        if d:
            w(d)
            w("")
        if req:
            w("Required: " + ", ".join(f"`{r}`" for r in req))
            w("")
        if a:
            w("| slot | range | notes |")
            w("|---|---|---|")
            for n, s in a.items():
                rng = s.get("range", "string")
                if rng in enums:
                    rng = f"[{rng}](#{rng.lower()})"
                flags = []
                if s.get("required"):
                    flags.append("required")
                if s.get("multivalued"):
                    flags.append("multivalued")
                if s.get("identifier"):
                    flags.append("identifier")
                desc = one_line(s.get("description"), 110)
                note = ("; ".join(flags) + (". " if flags and desc else "") + desc).strip()
                star = "*" if s.get("required") else ""
                w(f"| `{n}`{star} | {rng} | {note} |")
        w("")

    # Enums
    w("## Enums")
    w("")
    for name in sorted(enums):
        e = enums[name]
        pv = e.get("permissible_values") or {}
        w(f"### {name}")
        d = one_line(e.get("description"), 200)
        if d:
            w(d)
        w("")
        w(", ".join(f"`{v}`" for v in pv))
        w("")
    return "\n".join(lines) + "\n"


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--schema-dir")
    ap.add_argument("--out", default=str(DEFAULT_OUT))
    args = ap.parse_args()
    schema_dir = find_schema_dir(args.schema_dir)
    text = render(load_schemas(schema_dir), schema_dir)
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(text)
    print(f"wrote {out} ({len(text.splitlines())} lines)")


if __name__ == "__main__":
    main()
